/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import integrante.Participante;
import integrante.Responsavel;
import javax.swing.JOptionPane;

/**
 *
 * @author Valde
 */
public class CadastroDePessoal extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public CadastroDePessoal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JTabbedPane();
        jpEquipeOrganizadora = new javax.swing.JPanel();
        jpParticipante = new javax.swing.JPanel();
        lblNomeParticipanteOuResponsavel = new javax.swing.JLabel();
        lblEmailParticipanteOuResponsavel = new javax.swing.JLabel();
        lblTelefoneParticipanteOuResponsavel = new javax.swing.JLabel();
        txtNomeParticipanteOuResponsavel = new javax.swing.JTextField();
        txtTelefoneParticipanteOuResponsavel = new javax.swing.JTextField();
        txtEmailParticipanteOuResponsavel = new javax.swing.JTextField();
        btSalvarParticipanteOuResponsavel = new javax.swing.JButton();
        jcResponsavelOuParticipante = new javax.swing.JComboBox();
        jcResponsavelOuParticipanteAtividade = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpPrincipal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jpEquipeOrganizadoraLayout = new javax.swing.GroupLayout(jpEquipeOrganizadora);
        jpEquipeOrganizadora.setLayout(jpEquipeOrganizadoraLayout);
        jpEquipeOrganizadoraLayout.setHorizontalGroup(
            jpEquipeOrganizadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        jpEquipeOrganizadoraLayout.setVerticalGroup(
            jpEquipeOrganizadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jpPrincipal.addTab("Equipe Org.", jpEquipeOrganizadora);

        lblNomeParticipanteOuResponsavel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeParticipanteOuResponsavel.setText("Nome");

        lblEmailParticipanteOuResponsavel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmailParticipanteOuResponsavel.setText("Email");

        lblTelefoneParticipanteOuResponsavel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTelefoneParticipanteOuResponsavel.setText("Telefone");

        txtNomeParticipanteOuResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeParticipanteOuResponsavelActionPerformed(evt);
            }
        });

        txtEmailParticipanteOuResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailParticipanteOuResponsavelActionPerformed(evt);
            }
        });

        btSalvarParticipanteOuResponsavel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvarParticipanteOuResponsavel.setText("Salvar");
        btSalvarParticipanteOuResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarParticipanteOuResponsavelActionPerformed(evt);
            }
        });

        jcResponsavelOuParticipante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcResponsavelOuParticipante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Participante", "Responsável" }));
        jcResponsavelOuParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcResponsavelOuParticipanteActionPerformed(evt);
            }
        });

        jcResponsavelOuParticipanteAtividade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcResponsavelOuParticipanteAtividade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Minicurso", "Mesa Redonda", "Feira", "Palestra" }));
        jcResponsavelOuParticipanteAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcResponsavelOuParticipanteAtividadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpParticipanteLayout = new javax.swing.GroupLayout(jpParticipante);
        jpParticipante.setLayout(jpParticipanteLayout);
        jpParticipanteLayout.setHorizontalGroup(
            jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpParticipanteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpParticipanteLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jcResponsavelOuParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jcResponsavelOuParticipanteAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btSalvarParticipanteOuResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpParticipanteLayout.createSequentialGroup()
                        .addGroup(jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTelefoneParticipanteOuResponsavel)
                            .addGroup(jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEmailParticipanteOuResponsavel)
                                .addComponent(lblNomeParticipanteOuResponsavel)))
                        .addGap(28, 28, 28)
                        .addGroup(jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeParticipanteOuResponsavel, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(txtEmailParticipanteOuResponsavel)
                            .addComponent(txtTelefoneParticipanteOuResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jpParticipanteLayout.setVerticalGroup(
            jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpParticipanteLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeParticipanteOuResponsavel)
                    .addComponent(txtNomeParticipanteOuResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailParticipanteOuResponsavel)
                    .addComponent(txtEmailParticipanteOuResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefoneParticipanteOuResponsavel)
                    .addComponent(txtTelefoneParticipanteOuResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcResponsavelOuParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcResponsavelOuParticipanteAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalvarParticipanteOuResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jcResponsavelOuParticipante.getAccessibleContext().setAccessibleDescription("");

        jpPrincipal.addTab("Participante ou Responsável", jpParticipante);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarParticipanteOuResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarParticipanteOuResponsavelActionPerformed

        if(txtNomeParticipanteOuResponsavel.getText().isEmpty() || txtEmailParticipanteOuResponsavel.getText().isEmpty() || txtTelefoneParticipanteOuResponsavel.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!!");
            LimpaOsCamposDaInterfaceParticipanteOuResponsavel();

        } else if (jcResponsavelOuParticipante.getSelectedItem().equals("Participante")){
            Participante participante = new Participante(txtNomeParticipanteOuResponsavel.getText(), txtTelefoneParticipanteOuResponsavel.getText(), txtEmailParticipanteOuResponsavel.getText());
         
            JOptionPane.showMessageDialog(null, participante.informaNome() + " cadastrado(a) com sucesso!");
            LimpaOsCamposDaInterfaceParticipanteOuResponsavel();
        } else {
            Responsavel responsavel = new Responsavel(txtNomeParticipanteOuResponsavel.getText(), txtTelefoneParticipanteOuResponsavel.getText(), txtEmailParticipanteOuResponsavel.getText());
            JOptionPane.showMessageDialog(null, responsavel.informaNome() + " cadastrado(a) com sucesso!");
            LimpaOsCamposDaInterfaceParticipanteOuResponsavel();
        }

    }//GEN-LAST:event_btSalvarParticipanteOuResponsavelActionPerformed

   // private void relacionaParticipanteAAtividade(TipoAtividade TA, Participante P){
    //   TA.AdicionarParticipante(P);
    //}
    
    private void txtEmailParticipanteOuResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailParticipanteOuResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailParticipanteOuResponsavelActionPerformed

    private void txtNomeParticipanteOuResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeParticipanteOuResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeParticipanteOuResponsavelActionPerformed

    private void jcResponsavelOuParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcResponsavelOuParticipanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcResponsavelOuParticipanteActionPerformed

    private void jcResponsavelOuParticipanteAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcResponsavelOuParticipanteAtividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcResponsavelOuParticipanteAtividadeActionPerformed
    
    private void LimpaOsCamposDaInterfaceParticipanteOuResponsavel(){
        txtNomeParticipanteOuResponsavel.setText("");
        txtTelefoneParticipanteOuResponsavel.setText("");
        txtEmailParticipanteOuResponsavel.setText("");
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDePessoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDePessoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDePessoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDePessoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDePessoal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvarParticipanteOuResponsavel;
    private javax.swing.JComboBox jcResponsavelOuParticipante;
    private javax.swing.JComboBox jcResponsavelOuParticipanteAtividade;
    private javax.swing.JPanel jpEquipeOrganizadora;
    private javax.swing.JPanel jpParticipante;
    private javax.swing.JTabbedPane jpPrincipal;
    private javax.swing.JLabel lblEmailParticipanteOuResponsavel;
    private javax.swing.JLabel lblNomeParticipanteOuResponsavel;
    private javax.swing.JLabel lblTelefoneParticipanteOuResponsavel;
    private javax.swing.JTextField txtEmailParticipanteOuResponsavel;
    private javax.swing.JTextField txtNomeParticipanteOuResponsavel;
    private javax.swing.JTextField txtTelefoneParticipanteOuResponsavel;
    // End of variables declaration//GEN-END:variables
}
