/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import integrante.Participante;
import javax.swing.JOptionPane;

/**
 *
 * @author Valde
 */
public class CadastroDePessoal extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public CadastroDePessoal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JTabbedPane();
        jpEquipeOrganizadora = new javax.swing.JPanel();
        jpResponsavel = new javax.swing.JPanel();
        jpParticipante = new javax.swing.JPanel();
        lblNomeParticipante = new javax.swing.JLabel();
        lblEmailParticipante = new javax.swing.JLabel();
        lblTelefoneParticipante = new javax.swing.JLabel();
        txtNomeParticipante = new javax.swing.JTextField();
        txtTelefoneParticipante = new javax.swing.JTextField();
        txtEmailParticipante = new javax.swing.JTextField();
        btLimparParticipante = new javax.swing.JButton();
        btSalvarParticipante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpPrincipal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jpEquipeOrganizadoraLayout = new javax.swing.GroupLayout(jpEquipeOrganizadora);
        jpEquipeOrganizadora.setLayout(jpEquipeOrganizadoraLayout);
        jpEquipeOrganizadoraLayout.setHorizontalGroup(
            jpEquipeOrganizadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jpEquipeOrganizadoraLayout.setVerticalGroup(
            jpEquipeOrganizadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jpPrincipal.addTab("Equipe Org.", jpEquipeOrganizadora);

        javax.swing.GroupLayout jpResponsavelLayout = new javax.swing.GroupLayout(jpResponsavel);
        jpResponsavel.setLayout(jpResponsavelLayout);
        jpResponsavelLayout.setHorizontalGroup(
            jpResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jpResponsavelLayout.setVerticalGroup(
            jpResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jpPrincipal.addTab("Responsável", jpResponsavel);

        lblNomeParticipante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeParticipante.setText("Nome");

        lblEmailParticipante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmailParticipante.setText("Email");

        lblTelefoneParticipante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTelefoneParticipante.setText("Telefone");

        txtNomeParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeParticipanteActionPerformed(evt);
            }
        });

        txtEmailParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailParticipanteActionPerformed(evt);
            }
        });

        btLimparParticipante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimparParticipante.setText("Limpar");
        btLimparParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparParticipanteActionPerformed(evt);
            }
        });

        btSalvarParticipante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvarParticipante.setText("Salvar");
        btSalvarParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarParticipanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpParticipanteLayout = new javax.swing.GroupLayout(jpParticipante);
        jpParticipante.setLayout(jpParticipanteLayout);
        jpParticipanteLayout.setHorizontalGroup(
            jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpParticipanteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTelefoneParticipante)
                    .addGroup(jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblEmailParticipante)
                        .addComponent(lblNomeParticipante)))
                .addGap(28, 28, 28)
                .addGroup(jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNomeParticipante, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                        .addComponent(txtEmailParticipante)
                        .addComponent(txtTelefoneParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpParticipanteLayout.createSequentialGroup()
                        .addComponent(btLimparParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btSalvarParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jpParticipanteLayout.setVerticalGroup(
            jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpParticipanteLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeParticipante)
                    .addComponent(txtNomeParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailParticipante)
                    .addComponent(txtEmailParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefoneParticipante)
                    .addComponent(txtTelefoneParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jpParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalvarParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jpPrincipal.addTab("Participante", jpParticipante);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeParticipanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeParticipanteActionPerformed

    private void txtEmailParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailParticipanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailParticipanteActionPerformed

    private void btSalvarParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarParticipanteActionPerformed
        
        if(txtNomeParticipante.getText().isEmpty() || txtEmailParticipante.getText().isEmpty() || txtTelefoneParticipante.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!!");
            LimpaCamposInterfaceParticipante();
            
        } else {
            Participante participante = new Participante(txtNomeParticipante.getText(), txtTelefoneParticipante.getText(), txtEmailParticipante.getText());
            JOptionPane.showMessageDialog(null, participante.informaNome() + " cadastrado(a) com sucesso!");
            LimpaCamposInterfaceParticipante();
        }
             
    }//GEN-LAST:event_btSalvarParticipanteActionPerformed
    
    private void LimpaCamposInterfaceParticipante(){
        txtNomeParticipante.setText("");
        txtTelefoneParticipante.setText("");
        txtEmailParticipante.setText("");
    }
    private void btLimparParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparParticipanteActionPerformed
        txtNomeParticipante.setText("");
        txtTelefoneParticipante.setText("");
        txtEmailParticipante.setText("");
    }//GEN-LAST:event_btLimparParticipanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDePessoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDePessoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDePessoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDePessoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDePessoal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimparParticipante;
    private javax.swing.JButton btSalvarParticipante;
    private javax.swing.JPanel jpEquipeOrganizadora;
    private javax.swing.JPanel jpParticipante;
    private javax.swing.JTabbedPane jpPrincipal;
    private javax.swing.JPanel jpResponsavel;
    private javax.swing.JLabel lblEmailParticipante;
    private javax.swing.JLabel lblNomeParticipante;
    private javax.swing.JLabel lblTelefoneParticipante;
    private javax.swing.JTextField txtEmailParticipante;
    private javax.swing.JTextField txtNomeParticipante;
    private javax.swing.JTextField txtTelefoneParticipante;
    // End of variables declaration//GEN-END:variables
}
